# Generated by Django 5.0 on 2023-12-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='number_of_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose',
            field=models.CharField(choices=[('office', 'Office'), ('restaurant', 'Restaurant')], max_length=50),
        ),
    ]
