# Generated by Django 5.0 on 2023-12-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_alter_visitor_first_name_alter_visitor_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='number_of_people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
